import Verbose.Tactics.Notations
import Verbose.German.Assume
import Verbose.German.By
import Verbose.German.Calc
import Verbose.German.Claim
import Verbose.German.Fix
import Verbose.German.Lets
import Verbose.German.Since
import Verbose.German.We
import Verbose.German.Widget
import Verbose.German.Statements
