import Verbose.German.Assume
import Verbose.German.By
import Verbose.German.Since
import Verbose.German.Claim
import Verbose.German.Fix
import Verbose.German.Lets
import Verbose.German.Set
import Verbose.German.We
import Verbose.German.Calc
